### ISSUE TITLE
Question: Is there a way migrate file from slow pool to system pool when file has been accessed. 

### ISSUE THREAD

**Issue by patirot** [nhaustein/spectrum-scale-policy-scripts#1]
sorry for open this question, but I am quite confuse this : Is there a way to auto migrate file from slow pool to system pool when file has been accessed.

**Comment by nhaustein** [comment]
No, this is not possible upon access. Auto migration only works if the high threshold of a pool is met. All other operations have to be done manually or scheduled using the policy engine. Get more information about policies from this [paper](https://www.ibm.com/support/pages/node/6260749).
