### ISSUE TITLE
typos in example file and written example. 

### ISSUE THREAD

**Issue by ewahl-osc** [nhaustein/spectrum-scale-policy-scripts#2]
Examples have typos that will keep them from running.  Two left parens on list-immutable.txt, and on example page 
  https://github.com/IBM/spectrum-scale-policy-scripts/tree/master/immutable  

ie:  
define(  exclude_list,
  (PATH_NAME LIKE '%/.SpaceMan/%' OR
   PATH_NAME LIKE '%/.ltfsee/%' OR
   PATH_NAME LIKE '%/.mmSharedTmpDir/%' OR
   PATH_NAME LIKE '%/.snapshots/%' OR
   NAME LIKE '.mmbackupShadow%' OR
   NAME LIKE 'mmbackup%')

^^ missing 2nd right paren.
Gives amusing errors in m4 though. 

/usr/bin/m4:stdin:2: ERROR: end of file in argument list
Error on popen/pclose(/usr/bin/m4   >'/fs/ess/policy_tmp//mmPolicy.policy.75163.6929E8C4'): rc=1.
[E:1] Error macro expanding policy text.
[E] Summary of errors:: _serious unclassified errors:1.
mmapplypolicy: Command failed. Examine previous error messages to determine cause.

...

**Comment by nhaustein** [comment]
Thanks for sharing this typo, corrected in.
